apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque

stringData:
  MYSQL_PSW: {{ .Values.secret.data.MYSQL_PSW | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.data.MYSQL_ROOT_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secret.data.JWT_SECRET | quote }}
  FLORACODEX_KEY: {{ .Values.secret.data.FLORACODEX_KEY | quote }}
