apiVersion: v2
name: plant-it-enhanced
description: Self-hosted gardening and private field-journal companion
type: application
version: 0.15.3
appVersion: "0.15.3"
icon: https://github.com/t0n003c/plant-it-enhanced/blob/main/images/plant-it-logo.png?raw=true
keywords:
  - plants
  - companion
sources:
  - https://github.com/t0n003c/plant-it-enhanced
maintainers:
  - name: t0n003c
    url: https://github.com/t0n003c
