package com.github.mdeluise.plantit.exception.error;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    USER_UNAUTHORIZED,
    INTERNAL_SERVER_ERROR,
    AUTHENTICATION_ERROR,
    TOO_MANY_REQUESTS,
    CARE_PROVIDER_NOT_CONFIGURED,
    CARE_PROVIDER_UNAVAILABLE,
}
